trigger:
  branches:
    include:
      - main

variables:
  - name: ACR_NAME
    value: "f2kwkhdb8vhvacr"
  - name: IMAGE_NAME
    value: "samples/hello-world"

  - name: AZURE_SUBSCRIPTION_SERVICE_CONNECTION
    value: "github.com_anhnguyenkim-agilityio"

pool:
  name: Default

stages:
# Build and push image
- stage: Build
  displayName: Build & Push to ACR
  jobs:
  - job: Build
    steps:

    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: "$(AZURE_SUBSCRIPTION_SERVICE_CONNECTION)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)

    - script: |
        IMAGE_TAG=$(Build.BuildId)
        echo "##vso[task.setvariable variable=imageTag]$IMAGE_TAG"
        echo "Building image: $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$IMAGE_TAG"

        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$IMAGE_TAG .
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$IMAGE_TAG
      displayName: "Build & Push Docker Image"
  # - stage: Deploy
  #   displayName: "Deploy SWA per Environment"
  #   jobs:
  #     - job: Deploy
  #       displayName: "Deploy Static Web App"
  #       pool:
  #         name: Default
  #       steps:
  #         - checkout: self

  #         - script: |
  #             if [ "$(Build.SourceBranchName)" == "main" ]; then
  #               echo "##vso[task.setvariable variable=ENV]dev"
  #             fi
  #           displayName: "Select environment token"

  #         - task: AzureContainerApps@1
  #           inputs:
  #             appSourcePath: '$(Build.SourcesDirectory)'
  #             azureSubscription: '$(AZURE_SUBSCRIPTION_SERVICE_CONNECTION)'
  #             acrName: '$(ACR_NAME)'
  #             containerAppName: 'my-container-app'
  #             resourceGroup: 'my-container-app-rg'
