trigger:
  branches:
    include:
      - main

variables:
  - name: ACR_NAME
    value: "f2kwkhdb8vhvacr"
  - name: IMAGE_NAME
    value: "samples/hello-world"

  - name: GITHUB_SERVICE_CONNECTION
    value: "github.com_anhnguyenkim-agilityio"

  - name: AZURE_SUBSCRIPTION_SERVICE_CONNECTION
    value: "AzureConnection"

  - name: containerApps
    value: "dev-app"

pool:
  name: Default

resources:
  repositories:
  - repository: self
    type: github
    name: $(GITHUB_SERVICE_CONNECTION)/my-first-container-app

stages:
# Build and push image
- stage: Build
  displayName: Build & Push to ACR
  jobs:
  - job: Build
    steps:
    # Set IMAGE_TAG and RG_NAME
    - bash: |
        echo "Branch name: $(Build.SourceBranchName)"
        # Detect environment from branch
        if [ "$(Build.SourceBranchName)" = "main" ]; then
          ENV_NAME="dev"
        elif [ "$(Build.SourceBranchName)" = "staging" ]; then
          ENV_NAME="staging"
        else
          ENV_NAME="dev"
        fi

        SHORT_SHA=$(echo $(Build.SourceVersion) | cut -c1-7)
        IMAGE_TAG="${ENV_NAME}-$SHORT_SHA"
        RG_NAME="${ENV_NAME}-rg"
        echo "Image tag: $IMAGE_TAG"
        echo "Resource group: $RG_NAME"

        # # Export variables for use in subsequent steps in this job
        # export IMAGE_TAG="$IMAGE_TAG"
        # export RG_NAME="$RG_NAME"

        # Also set output variables for next stage
        echo "##vso[task.setvariable variable=imageTag;isOutput=true]$IMAGE_TAG"
        echo "##vso[task.setvariable variable=rgName;isOutput=true]$RG_NAME"
      name: SetImageTag
      displayName: "Set image tag"

    # Login to ACR
    - task: AzureCLI@2
      displayName: "Login to ACR"
      inputs:
        azureSubscription: "$(AZURE_SUBSCRIPTION_SERVICE_CONNECTION)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)

    # Build and push container image
    - bash: |
        echo "Building image: $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$IMAGE_TAG"
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$IMAGE_TAG .
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$IMAGE_TAG
      displayName: "Build & Push Docker Image"

- stage: Deploy
  displayName: "Deploy Container Apps"
  dependsOn: Build
  jobs:
    - job: Deploy
      variables:
        # Reference output from Build job
        IMAGE_TAG: $[ dependencies.Build.outputs['SetImageTag.imageTag'] ]
        RG_NAME: $[ dependencies.Build.outputs['SetImageTag.rgName'] ]
      steps:
      - task: AzureCLI@2
        displayName: "Deploy all apps"
        inputs:
          azureSubscription: "$(AZURE_SUBSCRIPTION_SERVICE_CONNECTION)"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Deploying image: $(IMAGE_NAME):$(IMAGE_TAG)"

            for app in $(containerApps); do
              echo "Updating $app ..."
              az containerapp update \
                --name $app \
                --resource-group $(RG_NAME) \
                --image "$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)"
            done


      # # App1 with 2 containers
      # az containerapp update \
      #   --name app1 \
      #   --resource-group $RG_NAME \
      #   --containers '[{"name":"frontend","image":"$(ACR_NAME).azurecr.io/frontend:'"$IMAGE_TAG"'"},
      #                  {"name":"backend","image":"$(ACR_NAME).azurecr.io/backend:'"$IMAGE_TAG"'"}]'