name: Azure Coontainer Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    env:
      ACR_NAME: anhnguyenkimacr
      CONTAINER_APP_NAME: local-api
      RESOURCE_GROUP: local-rg
      IMAGE_NAME: samples/hello-world
      LOCATION: westus2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Azure with SP credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

        # Log in to Azure Container Registry (ACR)
      - name: Azure ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build and push image to ACR
        run: |
          IMAGE_TAG=${{ github.sha }}
          az acr build \
            --registry $ACR_NAME \
            --resource-group rg-terraform-backend \
            --image $IMAGE_NAME:$IMAGE_TAG \
            .

      - name: Deploy to Container App
        run: |
          IMAGE_TAG=${{ github.sha }}
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
