name: Azure Container Apps CI/CD

on:
  push:
    branches:
      - dev
      - stag
      - main

env:
  ACR_NAME: f2kwkhdb8vhvacr
  IMAGE_NAME: samples/hello-world

jobs:

  build_and_push_acr:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.set-tag.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Determine ENV from branch
      - name: Set ENV
        id: set-env
        run: |
          if [[ "${GITHUB_REF_NAME}" != "dev" && "${GITHUB_REF_NAME}" != "stag" && "${GITHUB_REF_NAME}" != "main" ]]; then
            echo "Branch not configured for deployment. Exiting."
            exit 1
          fi
          # ENV="${GITHUB_REF_NAME}"
          ENV="dev"
          echo "ENV=${ENV}" >> $GITHUB_ENV

      - name: Set Image Tag
        id: set-tag
        run: |
          IMAGE_TAG="${ENV}-${GITHUB_SHA::7}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      # Login to ACR using Azure CLI (no password)
      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker Image
        run: docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.IMAGE_TAG }} .

      - name: Push Docker Image
        run: docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.IMAGE_TAG }}

  deploy_container:
    runs-on: ubuntu-latest
    needs: build_and_push_acr

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Dynamically map branch → ENV, RESOURCE_GROUP, CONTAINER_APP_NAME
      - name: Set environment and resource group
        id: set-env
        run: |
          # Only deploy from allowed branches
          if [[ "${GITHUB_REF_NAME}" != "dev" && "${GITHUB_REF_NAME}" != "stag" && "${GITHUB_REF_NAME}" != "main" ]]; then
            echo "Branch not configured for deployment. Exiting."
            exit 1
          fi

          ENV="dev"
          RESOURCE_GROUP="${ENV}-rg"
          CONTAINER_APP_NAME="${ENV}-app"

          echo "ENV=${ENV}" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=${RESOURCE_GROUP}" >> $GITHUB_ENV
          echo "CONTAINER_APP_NAME=${CONTAINER_APP_NAME}" >> $GITHUB_ENV

      # Deploy container app
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ needs.build_and_push_acr.outputs.image-tag }}
