name: Trigger auto deployment for local-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/local-api-AutoDeployTrigger-36cbec9a-0b4e-4711-a714-2e63ca575cba.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LOCALAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LOCALAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LOCALAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: anhnguyenkimacr.azurecr.io
          registryUsername: ${{ secrets.LOCALAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LOCALAPI_REGISTRY_PASSWORD }}
          containerAppName: local-api
          resourceGroup: local-rg
          imageToBuild: anhnguyenkimacr.azurecr.io/local-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


